version: '3'
services:
    app:
        container_name: apollo-next-graphql
        restart: always
        build: .
        ports: 
            - '3000:3000'
    # webserver:
    #     container_name: webserver
    #     restart: unless-stopped
    #     build: nginx
    #     ports: 
    #         - '80:80'      